### ISSUE TITLE
Can you provide more details Mark

### ISSUE THREAD

**Issue by ghost** [diemmarkus/MSTEx-CVL#1]
@diemmarkus Thank you for your hard work Mark.

Can you provide more details:
- What are the dependencies needed and which versions?
- How to install?
- How to use?

Waiting for your reply

**Comment by diemmarkus** [comment]
Hi,

I have updated the ![README](https://github.com/diemmarkus/MSTEx-CVL/blob/master/README.md) accordingly - please let me know if something is unclear

best,
markus
